### ISSUE TITLE
Bug Report | Error when disconnect

### ISSUE THREAD

**Issue by Jakaboii** [micartey/Cardinal-Anticheat#143]
What type of bug you want to report? Describe it here
Whenever I get punished, CAC throws this error into the console: https://hatebin.com/qqehectnyo

When does the bug occurr?
When being punished

Cardinal Version: 1.0005

Spigot Version: PaperSpigot 1.8.8

> **Attached Files  (Required)**
https://hatebin.com/qqehectnyo

**Comment by Jakaboii** [comment]
I did some more testing, and it seems that it seems to only happen when I get banned for Combat hacks

**Comment by Clientastisch** [comment]
It's because the packet injection and not because any check. That you see that error after getting kicked for Combat hacks ist just coincidence

**Comment by Jakaboii** [comment]
Ah, OK
