### ISSUE TITLE
Bug Report | Please help why it %Player%  UID format

### ISSUE THREAD

**Issue by EpicCatto** [micartey/Cardinal-Anticheat#150]
Cardinal Version:lastest

Spigot Version: 1.8.8

> **Attached Files  (Required)**
![image](https://user-images.githubusercontent.com/72650902/107111163-4359e700-6880-11eb-9273-23ac3f269f9a.png)

**Comment by VenusClietnt** [comment]
I pick the wrong category sorry :(

**Comment by SingleUserxd** [comment]
Are you using a custom ban core?

**Comment by VenusClietnt** [comment]
> Are you using a custom ban core?

yes !

**Comment by SingleUserxd** [comment]
Maybe that plugin can't ban the same user (name, uuid), again if is already banned

**Comment by VenusClietnt** [comment]
> Maybe that plugin can't ban the same user (name, uuid), again if is already banned

it wont work with advance ban too

**Comment by VenusClietnt** [comment]
I think it needs name format, not uid

**Comment by VenusClietnt** [comment]
i never get this problem with other anticheat

**Comment by micartey** [comment]
This ticket relates to an outdated version of cardinal anticheat. If the problem occurs again, the ticket can be reopened or a new ticket can be created.
