### ISSUE TITLE
Bug Report | Error on PlayerPreLoginEvent 1.12.2

### ISSUE THREAD

**Issue by GreenedDev** [micartey/Cardinal-Anticheat#156]
What type of bug you want to report? Describe it here
the bug freezes the server.

When does the bug occurr?
On PlayerPreLoginEvent

Cardinal Version:
I downloaded latest from releases like 5 minutes ago

Spigot Version:
Im using paper

> **Attached Files  (Required)**
[latest.log](https://github.com/micartey/Cardinal-Anticheat/files/9703184/latest.log)

**Comment by micartey** [comment]
Is this paper 1.12? And could you Export your current configuration and attach it here?

_/cac config export [name]_

**Comment by micartey** [comment]
No further information needed. 
This issue has been resolved.
