### ISSUE TITLE
Bypass | Jesus

### ISSUE THREAD

**Issue by FeuerMongoid** [micartey/Cardinal-Anticheat#159]
Hack Client: FDP

Hacking Type: Jesus

Link To Hacked Client: https://github.com/SkidderMC/FDPClient [DEV Build]

Cardinal Version:  2.0006

Spigot Version: 1.8

> **Attached Video (Required)**

https://user-images.githubusercontent.com/80965350/226119317-eb06d70a-e189-49a7-ade3-dc9856119d91.mp4

**Comment by micartey** [comment]
This issue should be fixed in version 2.1 of CAC with the new _Jesus Type D_ check that also detects a few more jesus bypasses than this
