### ISSUE TITLE
Bug Report | ViaVersion duplicating packets

### ISSUE THREAD

**Issue by jonesdevelopment** [micartey/Cardinal-Anticheat#161]
What type of bug you want to report? Describe it here
ViaVersion (or MC1.9+) duplicates packets/sends the position twice whenever you right click with a sword and sprint jump (in air).

**These checks false flag:**
NetFrequence Type A
PacketAnalysis Type A,B
Fly Type C
Speed Type D,I,G
NoSlowdown Type A
VPort Type A

When does the bug occurr?
→ Right clicking the sword will translate to a shield, which is causing the issues
> right click with a sword and sprint jump (in air).

Cardinal Version: (TEST SERVER)

Spigot Version: (TEST SERVER)

> **Attached Files  (Required)**

**Comment by jonesdevelopment** [comment]
Update: Only NoSlowdown Type A falsely flags on 1.9+ (tested on 1.16.5)
The other checks only false on 1.19+ (tested on 1.19.3)

**Comment by micartey** [comment]
I want to note that ViaVersion is shit

**Comment by micartey** [comment]
Should be fixed in 3.0.0
