### ISSUE TITLE
Bug Report | 1.9+ clients being kicked when attacking/interacting

### ISSUE THREAD

**Issue by jonesdevelopment** [micartey/Cardinal-Anticheat#162]
What type of bug you want to report? Describe it here
1.9+ clients are unable to attack (or interact with) any living/human entity.
If you try to do that, you'll be kicked from the server with a weird disconnect message.
→ Not sure if this is related to ViaVersion.

When does the bug occurr?
Start a client (1.9-1.19.X) and try attacking or interacting with any living/human entity.
→ This was tested on 1.19.3 and 1.16.5

Cardinal Version: (TEST SERVER)

Spigot Version: (TEST SERVER)

> **Attached Files  (Required)**

**Comment by micartey** [comment]
Should be fixed in 3.0.0
