### ISSUE TITLE
Bypass | Balance Timer 

### ISSUE THREAD

**Issue by micartey** [micartey/Cardinal-Anticheat#163]
Hack Client: idk

Hacking Type: Timer / NetFrequence

Cardinal Version: 3.0.0 (unofficial)

Spigot Version: Electron-1.8.8

**Comment by jonesdevelopment** [comment]
Electro???????????????????????????
![image](https://user-images.githubusercontent.com/73846784/235732059-d162d69f-679c-446a-81d8-9ab0e89597d1.png)

**Comment by micartey** [comment]
And it was 1.8.8 not 1.8.9 😱

**Comment by micartey** [comment]
Current progress: Partly fixed by adding a max amount of packets a player can be in debt
