### ISSUE TITLE
Feature Request | Plugin load is slowly

### ISSUE THREAD

**Issue by HackHsda** [micartey/Cardinal-Anticheat#167]
What features would you like added? Describe them here
Hello, I'm from China. If I use your plug-in, it will load very slowly because you are a cloud loader. I often can't load successfully in China for a day. Can you add servers in China or Hong Kong/Japan servers to load?

**Comment by micartey** [comment]
Hello @HackHsda,
Servers in Asia are currently not planned - I simply don't earn enough to be able to do that.
I will look into a cache-while-revalidating strategy in order to address this issue.

Can you tell me how long cardinal takes for you to load?

**Comment by HackHsda** [comment]
A day to two days, sometimes five hours
I have a Chinese server that may help you

**Comment by micartey** [comment]
Let me clarify: Your server says `Done in 24h` ?
Or what does the server when successfully loading Cardinal?

**Comment by HackHsda** [comment]
Yes

**Comment by micartey** [comment]
In my experience, the server kills itself when taking too long to start...
Can you send me a log file of your server starting when this happens?

**Comment by micartey** [comment]
In doing

**Comment by micartey** [comment]
The current caching implementation takes 20 seconds, depending on your storage type and speed.
It will be implemented with the loader for 4.0.0-alpha.4

**Comment by micartey** [comment]
To enable caching, you need to set the following environment variable:

```
export CARDINAL_CACHE=true
```
