### ISSUE TITLE
False Positive | Wrong jump motion value messes with prediction checks

### ISSUE THREAD

**Issue by jonesdevelopment** [micartey/Cardinal-Anticheat#170]
How do you trigger the false positive? Describe it here
- Go on a 1.12.2+ client (I tested it using Lunar 1.16.5)
- Don't move, only hold down space (jump)

Verbose Message
- Fly A - some extremely small Y offset (easy to replicate)
- Nofall A

Cardinal Version: latest, Community - The exact version did not show when running /cac

Spigot Version: 1.19.3 Purpur

**Comment by micartey** [comment]
Should be fixed.
Please validate!
