### ISSUE TITLE
Bug Report | PlayerTeleportEvent incompatibility with Citizens

### ISSUE THREAD

**Issue by jonesdevelopment** [micartey/Cardinal-Anticheat#171]
What type of bug you want to report? Describe it here
- After using Cardinal for a while, the console was filled with the same exception over and over again:
Exception: https://pastebin.com/7esPwGGG

When does the bug occurr?
- Whenever someone tries teleporting/is being teleported by the server
- Whenever the PlayerTeleportEvent is called

Cardinal Version: latest, Community - The exact version did not show when running /cac

Spigot Version: 1.19.3 Purpur

**Comment by micartey** [comment]
Should be fixed in the 4.0.0 release
