### ISSUE TITLE
False Positive | No Slowdown (ViaVersion)

### ISSUE THREAD

**Issue by jonesdevelopment** [micartey/Cardinal-Anticheat#184]
### Information

![image](https://github.com/micartey/Cardinal-Anticheat/assets/73846784/c2fe0439-69ae-47c0-a960-367a59dbb51a)

### When does the bug occure?

1.8 on 1.20 server
Right click with shield

### Cardinal Version

latest

### Spigot Version

1.20.4 Paper (cardinal.micartey.dev)

**Comment by micartey** [comment]
Should be fixed in the 4.1 Release
