### ISSUE TITLE
Bypass | Fly Bypass

### ISSUE THREAD

**Issue by bbb908** [micartey/Cardinal-Anticheat#188]
### Information

Fly bypass and the advantage of it is pretty obvious

### Client

Modified ThunderHack - link not available (private client)

### Cardinal Version

4 (test server version)

### Spigot Version

did /ver and the test server is running on 1.20.4

### Video

https://github.com/micartey/Cardinal-Anticheat/assets/105934310/4f5eb905-54fd-4d61-a7ea-e46fe5c3f679

### Additional information

The fly works as follows: Jump using motion values of +0.42y when on the same y level the fly started at and when it applies those values also spoof ground for a bit before returning to normal ground

**Comment by micartey** [comment]
Fixed by `Fly Type H` in `4.1.0`
