### ISSUE TITLE
False Positive | Speed false with high slowness

### ISSUE THREAD

**Issue by bbb908** [micartey/Cardinal-Anticheat#191]
### Information

You get slowness so high you can't walk then just jump and walk forward

### Verbose Message

Speed G

### Cardinal Version

4

### Spigot Version

1.20.4

### Video

https://github.com/micartey/Cardinal-Anticheat/assets/105934310/bb99ac8d-2bc2-40e3-9653-3878785d3078

### Additional information

Just add a little boost to maxSpeed while jumping ig

**Comment by micartey** [comment]
This should be fixed.
It was never a published change which I reverted now
