### ISSUE TITLE
Bypass | Fly

### ISSUE THREAD

**Issue by bbb908** [micartey/Cardinal-Anticheat#200]
### Information

It's the spartan fly bypass on lb nextgen

### Client

Liquidbounce NextGen 0.4.1
https://liquidbounce.net/ (obv)

### Cardinal Version

4.2.1-alpha-stable-2c551714

### Spigot Version

1.20.4

### Video

https://github.com/micartey/Cardinal-Anticheat/assets/105934310/94a53049-a413-47f0-9652-8c2dbdb767f8

### Additional information

Abuses it not flagging fly making it lagback but not to the ground

**Comment by micartey** [comment]
@bbb908 Your video is broken - please update

**Comment by bbb908** [comment]
This one works fine for me

**Comment by bbb908** [comment]
Ok github has gone back to panic attack video viewer I'll find a fix tmr

**Comment by jonesdevelopment** [comment]
Spartan Fly flags like crazy when I try to use it on latest CAC (nightly)
