### ISSUE TITLE
False Positive | Jesus

### ISSUE THREAD

**Issue by AgentNoobff** [micartey/Cardinal-Anticheat#202]
### Information

Walk on the edge of a block beside fluid.

### Verbose Message

Jesus Type A

### Cardinal Version

5.0.0-alpha-nightly-61c5d5e9

### Spigot Version

CarbonSpigot 1.8.8

### Video

https://streamable.com/fixhl2

**Comment by micartey** [comment]
Has been fixed in combination with the environment issue #204
