### ISSUE TITLE
Bypass | Fly/AirJump

### ISSUE THREAD

**Issue by AgentNoobff** [micartey/Cardinal-Anticheat#203]
### Information

Fly or AirJump bypass, allows you to jump on ghost blocks.

### Client

https://github.com/SkidderMC/FDPClient

### Cardinal Version

5.0.0-alpha-nightly-61c5d5e9

### Spigot Version

CarbonSpigot 1.8.8

### Video

https://streamable.com/yi4mv2

**Comment by micartey** [comment]
Is Fly B enabled?

**Comment by AgentNoobff** [comment]
Yes, Fly B is enabled.

**Comment by micartey** [comment]
How long can you jump and can you also move horizontal?

**Comment by AgentNoobff** [comment]
As shown in the video, we can jump one block at a time, infinitely. I can move horizontally without jumping but if I jump and move horizontally at the same time, it flags and sets me back.

**Comment by micartey** [comment]
Can you show that to me in the Publix testserver when I have time?

**Comment by AgentNoobff** [comment]
Yes. We can discuss the timing on Discord.

**Comment by micartey** [comment]
Nothing to do.

Nofall prevents this fly
