### ISSUE TITLE
Feature Request | Remember Flag

### ISSUE THREAD

**Issue by Jakaboii** [micartey/Cardinal-Anticheat#91]
**What features would you like added? Describe them here**
Could you make it so when you have /cac flag enabled, it'll stay enabled, even when you disconnect

And if you have it disabled, it'll stay disabled even when you disconnect

**Comment by micartey** [comment]
This feature whould need a database connection which is not handled by Cardinal anymore. For this reason I would like to reject the suggestion and recommend that you either write an addon yourself or ask in the discord if anyone has already written such an addon
